name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check JavaScript syntax
      run: node -c voice-replay-card.js

    - name: Validate file structure
      run: |
        # Check required files exist
        test -f voice-replay-card.js || (echo "voice-replay-card.js not found" && exit 1)
        test -f README.md || (echo "README.md not found" && exit 1)
        test -f hacs.json || (echo "hacs.json not found" && exit 1)
        test -f LICENSE || (echo "LICENSE not found" && exit 1)
        echo "✅ All required files present"

    - name: Validate HACS configuration
      run: |
        # Check if hacs.json is valid JSON and has required fields
        node -e "
          const hacs = JSON.parse(require('fs').readFileSync('hacs.json', 'utf8'));
          if (!hacs.name) throw new Error('Missing name field in hacs.json');
          if (!hacs.filename) throw new Error('Missing filename field in hacs.json');
          if (hacs.filename !== 'voice-replay-card.js') throw new Error('Filename should be voice-replay-card.js');
          console.log('✅ HACS configuration is valid');
        "

    - name: Check card version is defined
      run: |
        # Check if CARD_VERSION exists in the file
        if ! grep -q "CARD_VERSION = " voice-replay-card.js; then
          echo "Error: CARD_VERSION not found in voice-replay-card.js"
          exit 1
        fi
        
        VERSION=$(grep "CARD_VERSION = " voice-replay-card.js | sed -n "s/.*CARD_VERSION = '\(.*\)'.*/\1/p")
        echo "Card version: $VERSION"
        
        if [ -z "$VERSION" ]; then
          echo "Error: Could not extract version from voice-replay-card.js"
          exit 1
        fi
        
        echo "✅ Card version validation passed"

    - name: Basic JavaScript linting
      run: |
        # Check for common issues
        echo "Checking for common JavaScript issues..."
        
        # Check for console.log (should be console.info for production)
        if grep -n "console\.log(" voice-replay-card.js; then
          echo "Warning: console.log found - consider using console.info or console.warn"
        fi
        
        # Check for TODO/FIXME comments
        if grep -n "TODO\|FIXME" voice-replay-card.js; then
          echo "Info: TODO/FIXME comments found"
        fi
        
        # Check basic structure
        if ! grep -q "class VoiceReplayCard" voice-replay-card.js; then
          echo "Error: VoiceReplayCard class not found"
          exit 1
        fi
        
        if ! grep -q "customElements.define" voice-replay-card.js; then
          echo "Error: customElements.define not found"
          exit 1
        fi
        
        echo "✅ Basic linting checks passed"